server:
  port: 8010
spring:
  application:
    name: feign-demo-consumer
eureka:
  client:
    # 健康检查
    healthcheck:
      enabled: true
    serviceUrl:
      defaultZone: http://user:password123@localhost:8761/eureka
  instance:
    # 左下角显示ip地址
    prefer-ip-address: true
    # 显示应用名称:ip:instance id:端口
    instance-id: ${spring.application.name}:${spring.cloud.client.ipAddress}:${spring.application.instance_id:${server.port}}
logging:
  level:
    cn.dfun.consumer.feign.UserFeignClient: DEBUG

# 解决第一次请求报超时异常的方案：
# hystrix.command.default.execution.isolation.thread.timeoutInMilliseconds: 5000
# 或者：
# hystrix.command.default.execution.timeout.enabled: false
# 或者：索性禁用feign的hystrix支持
feign.hystrix.enabled: false